version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/markdown:/data/markdown
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - vectordb

  vectordb:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

name: gopilot

networks:
  gopilot:

volumes:
  gopilot: